# Generated by Django 5.2.1 on 2025-05-25 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarpatiNest_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mountain',
            options={'ordering': ['-altitude'], 'verbose_name': 'Munte', 'verbose_name_plural': 'Munți'},
        ),
        migrations.AddField(
            model_name='mountain',
            name='category',
            field=models.CharField(choices=[('carpati_meridionali', 'Carpații Meridionali'), ('carpati_orientali', 'Carpații Orientali'), ('carpati_occidentali', 'Carpații Occidentali')], default='carpati_meridionali', max_length=50, verbose_name='Categorie'),
        ),
    ]
