# Generated by Django 5.2.1 on 2025-05-28 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarpatiNest_app', '0002_alter_mountain_options_mountain_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='refuge',
            name='capacity',
        ),
        migrations.RemoveField(
            model_name='refuge',
            name='location',
        ),
        migrations.AlterField(
            model_name='refuge',
            name='altitude',
            field=models.IntegerField(blank=True, null=True, verbose_name='Altitudine (m)'),
        ),
        migrations.AlterField(
            model_name='refuge',
            name='description',
            field=models.TextField(blank=True, verbose_name='Descriere'),
        ),
    ]
