# Generated by Django 5.2.1 on 2025-05-28 14:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarpatiNest_app', '0003_remove_refuge_capacity_remove_refuge_location_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='refuge',
            options={'ordering': ['mountain', 'name'], 'verbose_name': 'Refugiu', 'verbose_name_plural': 'Refugii'},
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in_date', models.DateField(verbose_name='Data check-in')),
                ('check_out_date', models.DateField(verbose_name='Data check-out')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data creării')),
                ('status', models.CharField(choices=[('pending', 'În așteptare'), ('confirmed', 'Confirmată'), ('canceled', 'Anulată')], default='pending', max_length=20, verbose_name='Status')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Note')),
                ('refuge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='CarpatiNest_app.refuge', verbose_name='Refugiu')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL, verbose_name='Utilizator')),
            ],
            options={
                'verbose_name': 'Rezervare',
                'verbose_name_plural': 'Rezervări',
                'ordering': ['-created_at'],
            },
        ),
    ]
