# Generated by Django 5.2.1 on 2025-05-28 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarpatiNest_app', '0005_remove_booking_check_in_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='refuge',
            name='capacity',
            field=models.IntegerField(default=10, verbose_name='Capacitate'),
        ),
        migrations.AlterField(
            model_name='refuge',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Descriere'),
        ),
    ]
