# Generated by Django 5.2.1 on 2025-05-28 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarpatiNest_app', '0006_refuge_capacity_alter_refuge_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='RefugeImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='refuge_images/', verbose_name='Imagine')),
                ('description', models.CharField(blank=True, max_length=200, null=True, verbose_name='Descriere imagine')),
                ('refuge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='CarpatiNest_app.refuge')),
            ],
            options={
                'verbose_name': 'Imagine refugiu',
                'verbose_name_plural': 'Imagini refugii',
            },
        ),
    ]
