# Generated by Django 5.2.1 on 2025-05-30 09:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarpatiNest_app', '0007_refugeimage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, '1 - Nemulțumit'), (2, '2 - Satisfăcător'), (3, '3 - Bun'), (4, '4 - Foarte bun'), (5, '5 - Excelent')], verbose_name='Evaluare')),
                ('comment', models.TextField(verbose_name='Comentariu')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data creării')),
                ('refuge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='CarpatiNest_app.refuge', verbose_name='Refugiu')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL, verbose_name='Utilizator')),
            ],
            options={
                'verbose_name': 'Review',
                'verbose_name_plural': 'Reviews',
                'ordering': ['-created_at'],
            },
        ),
    ]
