# Generated by Django 5.2.1 on 2025-05-30 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarpatiNest_app', '0008_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='members_count',
            field=models.IntegerField(default=1, verbose_name='Număr de membri'),
        ),
    ]
