# Generated by Django 5.2.1 on 2025-06-06 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarpatiNest_app', '0009_booking_members_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='refuge',
            name='latitude',
            field=models.FloatField(blank=True, help_text='Coordonata latitudine pentru refugiu', null=True, verbose_name='Latitudine'),
        ),
        migrations.AddField(
            model_name='refuge',
            name='longitude',
            field=models.FloatField(blank=True, help_text='Coordonata longitudine pentru refugiu', null=True, verbose_name='Longitudine'),
        ),
    ]
